services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DB_PORT}:${POSTGRES_HOST}"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
