services:
  app:
    image: node:20
    env_file:
      - .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NODE_ENV: "${ENV}"
      PORT: "${APP_PORT}"
    volumes:
      - .:/app
    command: >
      bash -c "npm run prisma:gen && npm run prod"
